### ISSUE TITLE
only one default export allowed

### ISSUE THREAD

**Issue by thienpow** [scaphold-io/react-native-starter-kit#1]
"only one default export allowed per module" at app.js

**Comment by vning93** [comment]
Thanks for letting me know! Should be fixed now.

**Comment by thienpow** [comment]
still there are errors, i have to remove the multiple "default" in components/App/ as well as components/HackerNewsClone... after remove all these "default" it could shows the Welcome screen but still can't do the "registration" by pressing Let's Go.

**Comment by vning93** [comment]
Great catch. I just removed the rest of the extra "defaults" in the app. The registration functionality seems to be working fine for me. Make sure you click on the word itself since I don't think there's a container around it. Also, you must fill out the form and can't leave the email / password blank.

**Comment by thienpow** [comment]
ok if i am using your api url it can register... 

if using my api url
https://api.scaphold.io/graphql/964bd1f0-793a-4940-b24a-06546e854ca1
it doesn't work.
